{% set name = "ipydagred3" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35a8b6929073d14547866da5cbc1d36019921b93713cc4d6e062709172cc2e71

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - jupyter-packaging
    - setuptools
  run:
    - python >=3.7
    - ipywidgets >=7.5.1

test:
  imports:
    - ipydagred3

about:
  home: http://github.com/timkpaine/ipydagred3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ipywidgets based jupyterlab wrapper for the dagre-d3 directed acyclic graph charting library

  description: |
    ipywidgets based jupyterlab wrapper for the dagre-d3 directed acyclic graph charting library
  dev_url: https://github.com/timkpaine/ipydagred3

extra:
  recipe-maintainers:
    - timkpaine
