{% set name = "ipydagred3" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70248e6cd7ae9895d8739e053a7056da9c2c39886d9a8c4bb8ec1afbe7d2b845

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nodejs
    - yarn
    - hatchling >=1.3.1
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.5.1
  run_constrained:
    - jupyterlab >=4,<5

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipydagred3

about:
  home: http://github.com/timkpaine/ipydagred3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ipywidgets based jupyterlab wrapper for the dagre-d3 directed acyclic graph charting library

  description: |
    ipywidgets based jupyterlab wrapper for the dagre-d3 directed acyclic graph charting library
  dev_url: https://github.com/timkpaine/ipydagred3

extra:
  recipe-maintainers:
    - timkpaine
